### Regression problem to predict salary

In [7]:
#importing libraries

import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder, LabelEncoder

In [8]:
#importing dataset into dataframe

data = pd.read_csv("churn_modelling.csv")
data.head()

   RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [9]:
#dropping columns RowNumber, CustomerId, Surname

data = data.drop(columns=['RowNumber', 'CustomerId', 'Surname'])
data.head()

   CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0          619    France  Female  ...               1        101348.88       1
1          608     Spain  Female  ...               1        112542.58       0
2          502    France  Female  ...               0        113931.57       1
3          699    France  Female  ...               0         93826.63       0
4          850     Spain  Female  ...               1         79084.10       0

[5 rows x 11 columns]

In [10]:
#splitting data into train and test set.

x = data.drop(columns=['EstimatedSalary'])
y = data['EstimatedSalary']


x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=42)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(7500, 10)
(2500, 10)
(7500,)
(2500,)

In [11]:
x_train['Gender'].head()

4901      Male
4375      Male
6698    Female
9805      Male
1101      Male
Name: Gender, dtype: str

In [12]:
#encoding categorical feature 'Gender'

label_encoder = LabelEncoder()

x_train['Gender'] = label_encoder.fit_transform(x_train['Gender'])
x_test['Gender'] = label_encoder.transform(x_test['Gender'])

In [13]:
x_train['Gender'].head()

4901    1
4375    1
6698    0
9805    1
1101    1
Name: Gender, dtype: int64

In [ ]:
#encoding categorical feature 'Geography'

onehot_encoder = OneHotEncoder()

geography_train_arr = onehot_encoder.fit_transform(x_train['Geography']).toarray()
geography_test_arr = onehot_encoder.transform(x_test['Geography']).toarray()

geo_train_df = pd.DataFrame(geography_train_arr, columns=onehot_encoder.get_feature_names_out())
geo_test_df = pd.DataFrame(geography_test_arr, columns=onehot_encoder.get_feature_names_out())